export enum Platform {

    PEARSON = "PEARSON",
    MCGRAW_HILL = "MCGRAW_HILL",
    RIT_WEBWORK = "RIT_WEBWORK",
    RIT_MYCOURSES = "RIT_MYCOURSES",
    EXPERT_TA = "EXPERT_TA",
    CUSTOM = "CUSTOM"

}
